# -*- coding: utf-8 -*-
"""Set5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJWbtWlWvH_eihM12l1TxdKZLPafEunV
"""

#Write a program to find the sum of integers between a and b
a = int(input("Enter the first value: "))
b = int(input("Enter the second value: "))
upper_bound = max(a, b)
lower_bound = min(a, b)
total_sum = sum(range(lower_bound, upper_bound + 1))
print("The sum of the integers between the upper and lower bounds is :", total_sum)

#Write a program to find the factorial of a given number using a while loop
N = int(input("Enter the number"))
factorial = 1
i = 1
while i <= N:
  factorial = factorial*i
  i = i+1
  print(factorial)

#Write a program to print the sum of all the numbers in a list.
 list = [10,20,30,40,50,60,70,80,90,100]
 total_sum = sum(list)
 print("The total sum fo the list is : ",total_sum)

#Write a program to input an integer number and check whether the first digit of the number is even or odd
 Number = int(input("Enter the number = "))
 first_digit = Number % 10
 if first_digit % 2 == 0:
  print("The first digit of the number is even ")
else:
  print("The first digit of the number is odd ")

#Write a program to print the sum of individual digits of a given integer using a while statement (use the % operator).
X = int(input("Enter the number = "))
totalsum = 0
while X > 0:
  digit = X % 10
  totalsum += digit
  X = X // 10  # <-- FIXED: This updates X so the loop can eventually end
print(totalsum)

#Write a program to find the sum of the first and last digit of a given number.
Number = int(input("Enter the number = "))
last_digit = Number % 10
first_digit = Number
while first_digit >= 10:
  first_digit = first_digit // 10
print("The sum of the first and last digit is:", first_digit + last_digit)

#Write a program to print the multiplication table of a given number.
# 1. Take input from the user
num = int(input("Enter a number: "))

# 2. Loop from 1 to 10 and print the calculation directly
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

#Write a program to print the cube of numbers up to a given integer.
num = int(input("Enter a number: "))
Cube = num ** 3

print("The cube of the number is :",Cube)

#Write a program to check whether a given number is prime or not.
X = int(input("Enter the number: "))
is_prime = True
if X <= 1:
  is_prime = False
else:
  for i in range(2, X):
    if X % i == 0:
      is_prime = False
      break
if is_prime:
  print("The number is prime")
else:
  print("The number is not prime")

# 1. Ask the user how many prime numbers they want
n = int(input("Enter how many prime numbers to print: "))
count = 0
num = 2
print("The prime numbers are:")
while count < n:
    is_prime = True
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(num, end=" ")
        count = count + 1
    num = num + 1

#Write a program to generate the first n numbers of the Fibonacci series
n = int(input("Enter the number of Fibonacci terms (n): "))
a = 0
b = 1
print("\nThe Fibonacci series is:")
if n <= 0:
    print("Please enter a positive integer greater than 0.")
elif n == 1:
    print(a)
else:
    print(a, b, end=" ")
    for i in range(2, n):
        next_num = a + b
        print(next_num, end=" ")
        a = b
        b = next_num
print()

#Write a program to find the maximum and minimum number from 10 given numbers using for loop.
# Initialize variables
# Get the first number to set the initial maximum and minimum
first_num = int(input("Enter number 1: "))
max_num = first_num
min_num = first_num

# Use a for loop to get the remaining 9 numbers
for i in range(2, 11):
  num = int(input(f"Enter number {i}: "))

  # Update maximum if the current number is larger
  if num > max_num:
    max_num = num

  # Update minimum if the current number is smaller
  if num < min_num:
    min_num = num

# Display the final results
print("\nResults:")
print(f"The maximum number is: {max_num}")
print(f"The minimum number is: {min_num}")

#Write a program to find the maximum and minimum number from 10 given numbers using while loop.
 # Initialize variables and counter
max_num = None
min_num = None
count = 1

# Use a while loop to run 10 times
while count <= 10:
  num = int(input(f"Enter number {count}: "))

  # Set initial values on the first iteration
  if count == 1:
    max_num = num
    min_num = num
  else:
    # Update max and min
    if num > max_num:
      max_num = num
    if num < min_num:
      min_num = num

  count += 1

# Display the final results
print("\nResults:")
print(f"The maximum number is: {max_num}")
print(f"The minimum number is: {min_num}")